name: Scrape and Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run scraper
        env:
          SKIP_IMAGE_DOWNLOAD: '1'
        run: node scraper.js

      - name: Record scrape timestamp (force change)
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .last_scrape.txt
          echo "Wrote .last_scrape.txt with timestamp:" $(cat .last_scrape.txt)

      - name: Check for changes
        run: |
          echo "=== Git status ==="
          git status
          echo "=== Git diff ==="
          git diff products.json || echo "No diff for products.json"
          echo "=== Products.json info ==="
          ls -la products.json
          head -10 products.json

      - name: Commit and push changes (always)
        run: |
          set -e
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Stage products and timestamp marker so there is always something to commit
          git add products.json .last_scrape.txt || true
          # Always create a commit, even if nothing changed, to poke GitHub Pages
          git commit -m "Update products data - $(date -u +'%Y-%m-%dT%H:%M:%SZ')" --allow-empty || true
          # Push with up to 3 retries in case of race conditions
          for i in 1 2 3; do
            if git push origin HEAD:main; then
              echo "Pushed successfully on attempt $i"; break
            fi
            echo "Push failed (attempt $i). Rebasing and retrying..."
            git pull --rebase origin main || true
            sleep 2
          done
