name: Scrape and Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run scraper
        env:
          SKIP_IMAGE_DOWNLOAD: '1'
        run: node scraper.js

      - name: Check for changes
        run: |
          echo "=== Git status ==="
          git status
          echo "=== Git diff ==="
          git diff products.json || echo "No diff for products.json"
          echo "=== Products.json info ==="
          ls -la products.json
          head -10 products.json

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add products.json
          if ! git diff --staged --quiet; then
            echo "Changes detected, committing..."
            git commit -m "Update products data - $(date)"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
